---
abstract: 'Data converter for Petitcom mkII'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Petitcom
no_index:
  directory:
    - inc
    - t
requires:
  App::Rad: 1.04
  Compress::Zlib: 2.048
  GD: 2.46
  GD::Barcode: 1.15
  GD::Tiler: 0.11
  Path::Class: 0.26
  Term::ANSIColor: 3.01
  Unicode::Japanese: 0.49
  YAML: 0.84
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hayajo/p5-Data-Petitcom.git
version: 0.01
